site_name: Biodiversity Project Documentation
site_description: Technical documentation for biodiversity 
site_author: AIT

nav:
  - Home: index.md
  # - AIT team:
  #     - Score prediction: score.md
  #     - Data Documentation: data.md
  #     - Model Training: training.md
  #     - Hardware: hardware.md
  #     - Inference: inference.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true