site_name: Biodiversity Project Documentation
site_description: Technical documentation for biodiversity 
site_url: https://kaunghtetcho-22.github.io/mkdocs-bio/
site_author: AIT

nav:
  - Home: index.md
  # - AIT team:
  #     - Score prediction: score.md
  #     - Data Documentation: data.md
  #     - Model Training: training.md
  #     - Hardware: hardware.md
  #     - Inference: inference.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
      
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true
  - glightbox
  - with-pdf:
      output_path: pdf/biodiversity-docs.pdf
      cover_title: Biodiversity Project Documentation
      cover_subtitle: Technical documentation for biodiversity
      author: AIT
      toc_title: Table of Contents
      render_js: true
      enabled_if_env: ENABLE_PDF_EXPORT